// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK1Bj-MFMbPEsOf-hJb95IenBQB1JgSXc',
    appId: '1:178877072818:android:8f84ac501c3d4c20bd90ab',
    messagingSenderId: '178877072818',
    projectId: 'cryptobae',
    storageBucket: 'cryptobae.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIB4vStTfzp4Rgp9uWnfOYDqzvKGAHro',
    appId: '1:178877072818:web:63dc23b7ed4f0f95bd90ab',
    messagingSenderId: '178877072818',
    projectId: 'cryptobae',
    authDomain: 'cryptobae.firebaseapp.com',
    storageBucket: 'cryptobae.firebasestorage.app',
    measurementId: 'G-CDQT88P9C5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8F4USuEPfS0SVoFkG5Vyr0VDHAHeO7o',
    appId: '1:178877072818:ios:6724c2467ffd9b00bd90ab',
    messagingSenderId: '178877072818',
    projectId: 'cryptobae',
    storageBucket: 'cryptobae.firebasestorage.app',
    iosClientId: '178877072818-3ttid2r516oemf11ulbm3vmjvq6sclsd.apps.googleusercontent.com',
    iosBundleId: 'com.cryptobae.app',
  );

}